### ISSUE TITLE
Add option to disable/enable placeholder book in the enchanting table

### ISSUE THREAD

**Issue by sonuvaharris** [Eniripsa96/EnchantmentAPI#15]
I'd like an option in the config.yml for whether or not the placeholder book is displayed when using the enchanting table.

I'd edit this for myself, but the uploaded project is missing the pom.xml.

**Comment by Eniripsa96** [comment]
There isn't a pom.xml since I didn't set it up for maven. I haven't really been working on this project though, so I'm not sure if I'll add this. The placeholder book is also fairly essential for allowing anything to be enchanted, so the setting's usage would be minimal.
