### ISSUE TITLE
Having an issue

### ISSUE THREAD

**Issue by materialplane** [Eniripsa96/EnchantmentAPI#17]
Here's my skill in skillapi: https://i.imgur.com/jKsKnu6.png

Here it is in enchantmentapi:  https://pastebin.com/8Q3SCTq7

Here's the error I keep getting: https://pastebin.com/7eKBtd4h

This is what the skill looks like on the editor: https://i.imgur.com/Qfvpuam.png

I'm using the latest version for 1.12

**Comment by Eniripsa96** [comment]
Fixed in 1.0.3. The "skill: <skill_name>" was being lost after the first load. Add that line to each config again and you should be good to go.
