### ISSUE TITLE
Skill Enchantment Error - Right clicking while on cooldown

### ISSUE THREAD

**Issue by EnergizedBlast** [Eniripsa96/EnchantmentAPI#24]
https://pastebin.com/8iQX9UDP

This error seems to trigger with any SKILL enchantment that relies on the cast trigger. When the skill enchantment is on cooldown, right-clicking on an entity seems to trigger it; however, right clicking on blocks or empty space doesn't seem to cause problems. 
The skill enchantment used in this instance was a simple Cast > Projectile skill.

**Comment by Eniripsa96** [comment]
Fixed in 1.0.5
