### ISSUE TITLE
Anvil Broken 

### ISSUE THREAD

**Issue by erichoshaw** [Eniripsa96/EnchantmentAPI#5]
Field container = ContainerAnvilInventory.class.getDeclaredField("a");
(From MainAnvil.java)
this throws an exception every time the anvil is used, since i believe "a" is a private field
i also saw your comment there, figured you had some issues anyway

**Comment by Eniripsa96** [comment]
What server are you using?

**Comment by eric1299** [comment]
Spigot 1.8.3

**Comment by Eniripsa96** [comment]
It appears to be running the 1.8.1 code for some reason. I've tested on my own Spigot 1.8.3 and it worked fine. Try getting a later 1.8.3 build?

**Comment by eric1299** [comment]
Link?

**Comment by Eniripsa96** [comment]
http://getspigot.org/

**Comment by eric1299** [comment]
oh i thought you wanted me to get a newer build of enchantapi

**Comment by eric1299** [comment]
it tells me craftbukkit broke with a custom anvil inventory

**Comment by eric1299** [comment]
https://gist.github.com/eric1299/290e540bebda87f485ef

**Comment by Eniripsa96** [comment]
That says you're using 1.8.6 for a server, which I haven't built for

**Comment by eric1299** [comment]
It gave me the same error before, except 1.8.3

**Comment by eric1299** [comment]
i have tried 3 builds
1.8.3 - "craftbukkit broke anvil"
1.8.3 dev build - "anvil error"
1.8.6 dev build - " anvil error"
