### ISSUE TITLE
1.7 Style Enchanting Option (Enhancement)

### ISSUE THREAD

**Issue by gh0ztbuster** [Eniripsa96/EnchantmentAPI#6]
I personally like enchantments taking full levels and hate the new lapis lazuli requirement so I propose that you add an option too allow plugin users to select which enchanting version they prefer; the new 1.8 or the old 1.7 style.

**Comment by Eniripsa96** [comment]
The problem with this is the new servers don't let you even try to enchant without the lapis present. I could make it not consume the lapis, but it would still need to be in the slot, which I don't think is what you want.

**Comment by gh0ztbuster** [comment]
Yes it is, just like the protocol hack spigot did for 1.8

**Comment by kangarko** [comment]
@Eniripsa96  It is possible to insert the lapis lazuli manually. I achieved it with code: http://pastebin.com/KJfsRDGx
